Traceback (most recent call last):
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/pbellec/env/psy3018/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.svm import SVC
model_svm = SVC(decision_function_shape = 'ovo', random_state = 0, kernel='linear')
model_svm.fit(X_train, y_train)
model_svm.report
------------------

[0;31m-----------------------------------------------------------------[0m
[0;31mAttributeError[0m                  Traceback (most recent call last)
[0;32m<ipython-input-5-47a978fcb546>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mmodel_svm[0m [0;34m=[0m [0mSVC[0m[0;34m([0m[0mdecision_function_shape[0m [0;34m=[0m [0;34m'ovo'[0m[0;34m,[0m [0mrandom_state[0m [0;34m=[0m [0;36m0[0m[0;34m,[0m [0mkernel[0m[0;34m=[0m[0;34m'linear'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mmodel_svm[0m[0;34m.[0m[0mfit[0m[0;34m([0m[0mX_train[0m[0;34m,[0m [0my_train[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0mmodel_svm[0m[0;34m.[0m[0mreport[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mAttributeError[0m: 'SVC' object has no attribute 'report'
AttributeError: 'SVC' object has no attribute 'report'

